import 'dart:convert';
import 'dart:async';
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:shared_preferences/shared_preferences.dart';

enum TaskType { focus, flexible }
enum TaskStatus { pending, done, failed }

class Task {
  Task({required this.id, required this.title, required this.type, required this.start,
    required this.color, this.minutes = 30, this.deadline, this.status = TaskStatus.pending,
    this.snoozes = 0, this.snoozedUntil});
  String id, title; TaskType type; DateTime start; int color, minutes, snoozes; DateTime? deadline, snoozedUntil; TaskStatus status;
  DateTime get end => type == TaskType.focus ? start.add(Duration(minutes: minutes)) : (deadline ?? start.add(const Duration(hours: 1)));
  DateTime get alarm => snoozedUntil ?? start;
  bool get failed => status == TaskStatus.failed;
  Map<String,dynamic> toJson()=>{'id':id,'title':title,'type':type.index,'start':start.toIso8601String(),'color':color,'minutes':minutes,'deadline':deadline?.toIso8601String(),'status':status.index,'snoozes':snoozes,'snoozedUntil':snoozedUntil?.toIso8601String()};
  static Task fromJson(Map<String,dynamic> j)=>Task(id:j['id'],title:j['title'],type:TaskType.values[j['type']],start:DateTime.parse(j['start']),color:j['color'],minutes:j['minutes']??30,deadline:j['deadline']==null?null:DateTime.parse(j['deadline']),status:TaskStatus.values[j['status']??0],snoozes:j['snoozes']??0,snoozedUntil:j['snoozedUntil']==null?null:DateTime.parse(j['snoozedUntil']));
}

void main()=>runApp(const FocoApp());
class FocoApp extends StatefulWidget{const FocoApp({super.key});@override State<FocoApp> createState()=>_FocoState();}
class _FocoState extends State<FocoApp>{List<Task> tasks=[];DateTime day=DateUtils.dateOnly(DateTime.now());Timer? timer;DateTime now=DateTime.now();
 @override void initState(){super.initState();load();timer=Timer.periodic(const Duration(seconds:30),(_){setState(()=>now=DateTime.now());});}
 @override void dispose(){timer?.cancel();super.dispose();}
 Future<void> load()async{final p=await SharedPreferences.getInstance();final raw=p.getString('tasks');if(raw!=null)tasks=(jsonDecode(raw) as List).map((x)=>Task.fromJson(x)).toList();setState((){});}
 Future<void> save()async{final p=await SharedPreferences.getInstance();await p.setString('tasks',jsonEncode(tasks.map((x)=>x.toJson()).toList()));}
 bool get blocked=>tasks.any((x)=>x.failed);
 List<Task> get today=>tasks.where((x)=>DateUtils.isSameDay(x.start,day)).toList()..sort((a,b)=>a.start.compareTo(b.start));
 void failSweep(){for(final t in tasks){if(t.status==TaskStatus.pending && ((t.type==TaskType.flexible&&t.deadline!=null&&now.isAfter(t.deadline!))||(t.type==TaskType.focus&&now.isAfter(t.alarm.add(const Duration(minutes:2)))))){t.status=TaskStatus.failed;}}save();}
 @override Widget build(BuildContext c){failSweep();final h=MediaQuery.sizeOf(c).height;return MaterialApp(debugShowCheckedModeBanner:false,theme:ThemeData.dark(useMaterial3:true).copyWith(colorScheme:ColorScheme.fromSeed(seedColor:const Color(0xff4f86f7),brightness:Brightness.dark)),home:Scaffold(appBar:AppBar(title:Text(DateFormat('EEE, d MMM', 'pt_BR').format(day)),actions:[IconButton(onPressed:()=>setState(()=>day=day.subtract(const Duration(days:1))),icon:const Icon(Icons.chevron_left)),TextButton(onPressed:()=>setState(()=>day=DateUtils.dateOnly(DateTime.now())),child:const Text('Hoje')),IconButton(onPressed:()=>setState(()=>day=day.add(const Duration(days:1))),icon:const Icon(Icons.chevron_right))]),body:Column(children:[if(blocked)Material(color:Colors.red,child:InkWell(onTap:()=>resolve(tasks.firstWhere((x)=>x.failed)),child:const Padding(padding:EdgeInsets.all(12),child:Text('Resolva suas pendências antes de planejar coisas novas.',style:TextStyle(fontWeight:FontWeight.bold))))),Expanded(child:SingleChildScrollView(child:SizedBox(height:24*76,child:Stack(children:[for(int i=0;i<24;i++)Positioned(top:i*76,left:0,right:0,child:Row(children:[SizedBox(width:60,child:Text('${i.toString().padLeft(2,'0')}:00',textAlign:TextAlign.right)),const SizedBox(width:8),Expanded(child:Divider(color:Colors.white12))])),if(DateUtils.isSameDay(day,now))Positioned(top:(now.hour+now.minute/60)*76,left:0,right:0,child:Container(height:2,color:Colors.red)),...today.asMap().entries.map((e){final t=e.value;final top=(t.start.hour+t.start.minute/60)*76.0;final height=(t.end.difference(t.start).inMinutes/60*76).clamp(32.0,1000.0);return Positioned(top:top,left:t.type==TaskType.focus?72:64,right:12,height:height,child:GestureDetector(onTap:()=>t.failed?resolve(t):actions(t),child:Container(margin:const EdgeInsets.symmetric(vertical:2),padding:const EdgeInsets.all(9),decoration:BoxDecoration(color:t.failed?Colors.red.withOpacity(.25):Color(t.color).withOpacity(t.type==TaskType.focus?.85:.18),borderRadius:BorderRadius.circular(10),border:Border.all(color:t.failed?Colors.red:Color(t.color),width:t.failed?3:1)),child:Text('${t.failed?'⚠ ':''}${t.title}\n${DateFormat('HH:mm').format(t.start)} - ${DateFormat('HH:mm').format(t.end)}',style:const TextStyle(fontWeight:FontWeight.bold)))));})]))))]),floatingActionButton:FloatingActionButton.large(onPressed:blocked?null:()=>addTask(),child:Icon(blocked?Icons.lock:Icons.add)));}
 Future<void> addTask()async{final title=TextEditingController();TaskType type=TaskType.focus;TimeOfDay time=TimeOfDay.now();int mins=30;int color=0xff4f86f7;final ok=await showModalBottomSheet<bool>(context:context,isScrollControlled:true,builder:(_)=>StatefulBuilder(builder:(ctx,set){return Padding(padding:EdgeInsets.only(left:18,right:18,bottom:MediaQuery.viewInsetsOf(ctx).bottom+18,top:18),child:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:title,autofocus:true,decoration:const InputDecoration(hintText:'O que precisa acontecer?')),const SizedBox(height:12),DropdownButton<TaskType>(value:type,isExpanded:true,items:const[DropdownMenuItem(value:TaskType.focus,child:Text('Tarefa de Foco')),DropdownMenuItem(value:TaskType.flexible,child:Text('Janela Flexível'))],onChanged:(v)=>set(()=>type=v!)),ListTile(title:Text('Início: ${time.format(ctx)}'),onTap:()async{final x=await showTimePicker(context:ctx,initialTime:time);if(x!=null)set(()=>time=x);}),if(type==TaskType.focus)Slider(value:mins.toDouble(),min:15,max:120,divisions:7,label:'$mins min',onChanged:(v)=>set(()=>mins=v.round())),FilledButton(onPressed:()=>Navigator.pop(ctx,true),child:const Text('Salvar'))]));}));if(ok!=true||title.text.trim().isEmpty)return;final s=DateTime(day.year,day.month,day.day,time.hour,time.minute);tasks.add(Task(id:DateTime.now().microsecondsSinceEpoch.toString(),title:title.text.trim(),type:type,start:s,color:color,minutes:mins,deadline:type==TaskType.flexible?s.add(const Duration(hours:4)):null));await save();setState((){});}
 void actions(Task t){showModalBottomSheet(context:context,builder:(_)=>SafeArea(child:Column(mainAxisSize:MainAxisSize.min,children:[ListTile(title:Text(t.title)),ListTile(leading:const Icon(Icons.check),title:const Text('Concluir'),onTap:(){setState(()=>t.status=TaskStatus.done);save();Navigator.pop(context);}),if(t.snoozes<3)ListTile(leading:const Icon(Icons.snooze),title:Text('Adiar ${[10,5,2][t.snoozes]} min'),onTap:(){setState((){t.snoozedUntil=DateTime.now().add(Duration(minutes:[10,5,2][t.snoozes]));t.snoozes++;});save();Navigator.pop(context);}),ListTile(leading:const Icon(Icons.delete,color:Colors.red),title:const Text('Excluir manualmente'),onTap:(){setState(()=>tasks.remove(t));save();Navigator.pop(context);})]));}
 void resolve(Task t){showModalBottomSheet(context:context,isDismissible:false,builder:(_)=>SafeArea(child:Column(mainAxisSize:MainAxisSize.min,children:[Padding(padding:const EdgeInsets.all(16),child:Text('Falha: ${t.title}',style:const TextStyle(fontSize:18,fontWeight:FontWeight.bold))),ListTile(leading:const Icon(Icons.today),title:const Text('Reagendar para hoje'),onTap:(){setState((){t.start=DateTime.now();t.status=TaskStatus.pending;t.snoozes=0;});save();Navigator.pop(context);}),ListTile(leading:const Icon(Icons.event),title:const Text('Reagendar para amanhã'),onTap:(){setState((){t.start=DateTime.now().add(const Duration(days:1));t.status=TaskStatus.pending;t.snoozes=0;});save();Navigator.pop(context);}),ListTile(leading:const Icon(Icons.delete,color:Colors.red),title:const Text('Excluir e assumir desistência'),onTap:(){setState(()=>tasks.remove(t));save();Navigator.pop(context);})]));}
}
